apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu
        command: ["nvidia-smi",  "-L"]
        resources:
          limits:
            qnib.org/gpu: 1
      restartPolicy: Never

  backoffLimit: 4