apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi-0
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu
        command: ["/usr/bin/nvidia-smi", "-L"]
        resources:
          limits:
            qnib.org/gpu: 1
      restartPolicy: Never
